apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
  namespace: homework
spec:
  storageClassName: hw-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
